Fix recursive call of Call()
Since it encloses the error code to a Vim error (consider drop it)?
If it is recursively called, it can match against what it produced,
which makes a double wrap:
TypeError: TypeError: ...

We use E111: instead of E111 as pattern against Vim error to avoid this.